version: "3.8"

services:
  booking-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - booking-network

networks:
  booking-network:
    driver: bridge
