version: "3.8"

services:
  booking-web:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    container_name: booking-web-app
    restart: unless-stopped
    env_file:
      - .env
