// Country data with name, code (for flag), and dial code
const countries = [
  {
    name: "Việt Nam",
    code: "VN",
    dialCode: "+84",
    flag: "https://flagcdn.com/vn.svg",
  },
  {
    name: "Afghanistan",
    code: "AF",
    dialCode: "+93",
    flag: "https://flagcdn.com/af.svg",
  },
  {
    name: "Albania",
    code: "AL",
    dialCode: "+355",
    flag: "https://flagcdn.com/al.svg",
  },
  {
    name: "Algeria",
    code: "DZ",
    dialCode: "+213",
    flag: "https://flagcdn.com/dz.svg",
  },
  {
    name: "Andorra",
    code: "AD",
    dialCode: "+376",
    flag: "https://flagcdn.com/ad.svg",
  },
  {
    name: "Angola",
    code: "AO",
    dialCode: "+244",
    flag: "https://flagcdn.com/ao.svg",
  },
  {
    name: "Argentina",
    code: "AR",
    dialCode: "+54",
    flag: "https://flagcdn.com/ar.svg",
  },
  {
    name: "Armenia",
    code: "AM",
    dialCode: "+374",
    flag: "https://flagcdn.com/am.svg",
  },
  {
    name: "Australia",
    code: "AU",
    dialCode: "+61",
    flag: "https://flagcdn.com/au.svg",
  },
  {
    name: "Austria",
    code: "AT",
    dialCode: "+43",
    flag: "https://flagcdn.com/at.svg",
  },
  {
    name: "Azerbaijan",
    code: "AZ",
    dialCode: "+994",
    flag: "https://flagcdn.com/az.svg",
  },
  {
    name: "Bahamas",
    code: "BS",
    dialCode: "+1",
    flag: "https://flagcdn.com/bs.svg",
  },
  {
    name: "Bahrain",
    code: "BH",
    dialCode: "+973",
    flag: "https://flagcdn.com/bh.svg",
  },
  {
    name: "Bangladesh",
    code: "BD",
    dialCode: "+880",
    flag: "https://flagcdn.com/bd.svg",
  },
  {
    name: "Barbados",
    code: "BB",
    dialCode: "+1",
    flag: "https://flagcdn.com/bb.svg",
  },
  {
    name: "Belarus",
    code: "BY",
    dialCode: "+375",
    flag: "https://flagcdn.com/by.svg",
  },
  {
    name: "Belgium",
    code: "BE",
    dialCode: "+32",
    flag: "https://flagcdn.com/be.svg",
  },
  {
    name: "Belize",
    code: "BZ",
    dialCode: "+501",
    flag: "https://flagcdn.com/bz.svg",
  },
  {
    name: "Benin",
    code: "BJ",
    dialCode: "+229",
    flag: "https://flagcdn.com/bj.svg",
  },
  {
    name: "Bhutan",
    code: "BT",
    dialCode: "+975",
    flag: "https://flagcdn.com/bt.svg",
  },
  {
    name: "Bolivia",
    code: "BO",
    dialCode: "+591",
    flag: "https://flagcdn.com/bo.svg",
  },
  {
    name: "Bosnia and Herzegovina",
    code: "BA",
    dialCode: "+387",
    flag: "https://flagcdn.com/ba.svg",
  },
  {
    name: "Botswana",
    code: "BW",
    dialCode: "+267",
    flag: "https://flagcdn.com/bw.svg",
  },
  {
    name: "Brazil",
    code: "BR",
    dialCode: "+55",
    flag: "https://flagcdn.com/br.svg",
  },
  {
    name: "Brunei",
    code: "BN",
    dialCode: "+673",
    flag: "https://flagcdn.com/bn.svg",
  },
  {
    name: "Bulgaria",
    code: "BG",
    dialCode: "+359",
    flag: "https://flagcdn.com/bg.svg",
  },
  {
    name: "Burkina Faso",
    code: "BF",
    dialCode: "+226",
    flag: "https://flagcdn.com/bf.svg",
  },
  {
    name: "Burundi",
    code: "BI",
    dialCode: "+257",
    flag: "https://flagcdn.com/bi.svg",
  },
  {
    name: "Cambodia",
    code: "KH",
    dialCode: "+855",
    flag: "https://flagcdn.com/kh.svg",
  },
  {
    name: "Cameroon",
    code: "CM",
    dialCode: "+237",
    flag: "https://flagcdn.com/cm.svg",
  },
  {
    name: "Canada",
    code: "CA",
    dialCode: "+1",
    flag: "https://flagcdn.com/ca.svg",
  },
  {
    name: "Cape Verde",
    code: "CV",
    dialCode: "+238",
    flag: "https://flagcdn.com/cv.svg",
  },
  {
    name: "Central African Republic",
    code: "CF",
    dialCode: "+236",
    flag: "https://flagcdn.com/cf.svg",
  },
  {
    name: "Chad",
    code: "TD",
    dialCode: "+235",
    flag: "https://flagcdn.com/td.svg",
  },
  {
    name: "Chile",
    code: "CL",
    dialCode: "+56",
    flag: "https://flagcdn.com/cl.svg",
  },
  {
    name: "China",
    code: "CN",
    dialCode: "+86",
    flag: "https://flagcdn.com/cn.svg",
  },
  {
    name: "Colombia",
    code: "CO",
    dialCode: "+57",
    flag: "https://flagcdn.com/co.svg",
  },
  {
    name: "Comoros",
    code: "KM",
    dialCode: "+269",
    flag: "https://flagcdn.com/km.svg",
  },
  {
    name: "Costa Rica",
    code: "CR",
    dialCode: "+506",
    flag: "https://flagcdn.com/cr.svg",
  },
  {
    name: "Croatia",
    code: "HR",
    dialCode: "+385",
    flag: "https://flagcdn.com/hr.svg",
  },
  {
    name: "Cuba",
    code: "CU",
    dialCode: "+53",
    flag: "https://flagcdn.com/cu.svg",
  },
  {
    name: "Cyprus",
    code: "CY",
    dialCode: "+357",
    flag: "https://flagcdn.com/cy.svg",
  },
  {
    name: "Czech Republic",
    code: "CZ",
    dialCode: "+420",
    flag: "https://flagcdn.com/cz.svg",
  },
  {
    name: "Denmark",
    code: "DK",
    dialCode: "+45",
    flag: "https://flagcdn.com/dk.svg",
  },
  {
    name: "Egypt",
    code: "EG",
    dialCode: "+20",
    flag: "https://flagcdn.com/eg.svg",
  },
  {
    name: "Estonia",
    code: "EE",
    dialCode: "+372",
    flag: "https://flagcdn.com/ee.svg",
  },
  {
    name: "Ethiopia",
    code: "ET",
    dialCode: "+251",
    flag: "https://flagcdn.com/et.svg",
  },
  {
    name: "Fiji",
    code: "FJ",
    dialCode: "+679",
    flag: "https://flagcdn.com/fj.svg",
  },
  {
    name: "Finland",
    code: "FI",
    dialCode: "+358",
    flag: "https://flagcdn.com/fi.svg",
  },
  {
    name: "France",
    code: "FR",
    dialCode: "+33",
    flag: "https://flagcdn.com/fr.svg",
  },
  {
    name: "Germany",
    code: "DE",
    dialCode: "+49",
    flag: "https://flagcdn.com/de.svg",
  },
  {
    name: "Ghana",
    code: "GH",
    dialCode: "+233",
    flag: "https://flagcdn.com/gh.svg",
  },
  {
    name: "Greece",
    code: "GR",
    dialCode: "+30",
    flag: "https://flagcdn.com/gr.svg",
  },
  {
    name: "Hong Kong",
    code: "HK",
    dialCode: "+852",
    flag: "https://flagcdn.com/hk.svg",
  },
  {
    name: "Hungary",
    code: "HU",
    dialCode: "+36",
    flag: "https://flagcdn.com/hu.svg",
  },
  {
    name: "Iceland",
    code: "IS",
    dialCode: "+354",
    flag: "https://flagcdn.com/is.svg",
  },
  {
    name: "India",
    code: "IN",
    dialCode: "+91",
    flag: "https://flagcdn.com/in.svg",
  },
  {
    name: "Indonesia",
    code: "ID",
    dialCode: "+62",
    flag: "https://flagcdn.com/id.svg",
  },
  {
    name: "Iran",
    code: "IR",
    dialCode: "+98",
    flag: "https://flagcdn.com/ir.svg",
  },
  {
    name: "Iraq",
    code: "IQ",
    dialCode: "+964",
    flag: "https://flagcdn.com/iq.svg",
  },
  {
    name: "Ireland",
    code: "IE",
    dialCode: "+353",
    flag: "https://flagcdn.com/ie.svg",
  },
  {
    name: "Israel",
    code: "IL",
    dialCode: "+972",
    flag: "https://flagcdn.com/il.svg",
  },
  {
    name: "Italy",
    code: "IT",
    dialCode: "+39",
    flag: "https://flagcdn.com/it.svg",
  },
  {
    name: "Jamaica",
    code: "JM",
    dialCode: "+1",
    flag: "https://flagcdn.com/jm.svg",
  },
  {
    name: "Japan",
    code: "JP",
    dialCode: "+81",
    flag: "https://flagcdn.com/jp.svg",
  },
  {
    name: "Jordan",
    code: "JO",
    dialCode: "+962",
    flag: "https://flagcdn.com/jo.svg",
  },
  {
    name: "Kazakhstan",
    code: "KZ",
    dialCode: "+7",
    flag: "https://flagcdn.com/kz.svg",
  },
  {
    name: "Kenya",
    code: "KE",
    dialCode: "+254",
    flag: "https://flagcdn.com/ke.svg",
  },
  {
    name: "Korea, South",
    code: "KR",
    dialCode: "+82",
    flag: "https://flagcdn.com/kr.svg",
  },
  {
    name: "Kuwait",
    code: "KW",
    dialCode: "+965",
    flag: "https://flagcdn.com/kw.svg",
  },
  {
    name: "Kyrgyzstan",
    code: "KG",
    dialCode: "+996",
    flag: "https://flagcdn.com/kg.svg",
  },
  {
    name: "Laos",
    code: "LA",
    dialCode: "+856",
    flag: "https://flagcdn.com/la.svg",
  },
  {
    name: "Latvia",
    code: "LV",
    dialCode: "+371",
    flag: "https://flagcdn.com/lv.svg",
  },
  {
    name: "Lebanon",
    code: "LB",
    dialCode: "+961",
    flag: "https://flagcdn.com/lb.svg",
  },
  {
    name: "Libya",
    code: "LY",
    dialCode: "+218",
    flag: "https://flagcdn.com/ly.svg",
  },
  {
    name: "Lithuania",
    code: "LT",
    dialCode: "+370",
    flag: "https://flagcdn.com/lt.svg",
  },
  {
    name: "Luxembourg",
    code: "LU",
    dialCode: "+352",
    flag: "https://flagcdn.com/lu.svg",
  },
  {
    name: "Madagascar",
    code: "MG",
    dialCode: "+261",
    flag: "https://flagcdn.com/mg.svg",
  },
  {
    name: "Malaysia",
    code: "MY",
    dialCode: "+60",
    flag: "https://flagcdn.com/my.svg",
  },
  {
    name: "Maldives",
    code: "MV",
    dialCode: "+960",
    flag: "https://flagcdn.com/mv.svg",
  },
  {
    name: "Mali",
    code: "ML",
    dialCode: "+223",
    flag: "https://flagcdn.com/ml.svg",
  },
  {
    name: "Malta",
    code: "MT",
    dialCode: "+356",
    flag: "https://flagcdn.com/mt.svg",
  },
  {
    name: "Mexico",
    code: "MX",
    dialCode: "+52",
    flag: "https://flagcdn.com/mx.svg",
  },
  {
    name: "Monaco",
    code: "MC",
    dialCode: "+377",
    flag: "https://flagcdn.com/mc.svg",
  },
  {
    name: "Mongolia",
    code: "MN",
    dialCode: "+976",
    flag: "https://flagcdn.com/mn.svg",
  },
  {
    name: "Morocco",
    code: "MA",
    dialCode: "+212",
    flag: "https://flagcdn.com/ma.svg",
  },
  {
    name: "Myanmar",
    code: "MM",
    dialCode: "+95",
    flag: "https://flagcdn.com/mm.svg",
  },
  {
    name: "Nepal",
    code: "NP",
    dialCode: "+977",
    flag: "https://flagcdn.com/np.svg",
  },
  {
    name: "Netherlands",
    code: "NL",
    dialCode: "+31",
    flag: "https://flagcdn.com/nl.svg",
  },
  {
    name: "New Zealand",
    code: "NZ",
    dialCode: "+64",
    flag: "https://flagcdn.com/nz.svg",
  },
  {
    name: "Nigeria",
    code: "NG",
    dialCode: "+234",
    flag: "https://flagcdn.com/ng.svg",
  },
  {
    name: "Norway",
    code: "NO",
    dialCode: "+47",
    flag: "https://flagcdn.com/no.svg",
  },
  {
    name: "Pakistan",
    code: "PK",
    dialCode: "+92",
    flag: "https://flagcdn.com/pk.svg",
  },
  {
    name: "Palestine",
    code: "PS",
    dialCode: "+970",
    flag: "https://flagcdn.com/ps.svg",
  },
  {
    name: "Panama",
    code: "PA",
    dialCode: "+507",
    flag: "https://flagcdn.com/pa.svg",
  },
  {
    name: "Paraguay",
    code: "PY",
    dialCode: "+595",
    flag: "https://flagcdn.com/py.svg",
  },
  {
    name: "Peru",
    code: "PE",
    dialCode: "+51",
    flag: "https://flagcdn.com/pe.svg",
  },
  {
    name: "Philippines",
    code: "PH",
    dialCode: "+63",
    flag: "https://flagcdn.com/ph.svg",
  },
  {
    name: "Poland",
    code: "PL",
    dialCode: "+48",
    flag: "https://flagcdn.com/pl.svg",
  },
  {
    name: "Portugal",
    code: "PT",
    dialCode: "+351",
    flag: "https://flagcdn.com/pt.svg",
  },
  {
    name: "Qatar",
    code: "QA",
    dialCode: "+974",
    flag: "https://flagcdn.com/qa.svg",
  },
  {
    name: "Romania",
    code: "RO",
    dialCode: "+40",
    flag: "https://flagcdn.com/ro.svg",
  },
  {
    name: "Russia",
    code: "RU",
    dialCode: "+7",
    flag: "https://flagcdn.com/ru.svg",
  },
  {
    name: "Rwanda",
    code: "RW",
    dialCode: "+250",
    flag: "https://flagcdn.com/rw.svg",
  },
  {
    name: "Saudi Arabia",
    code: "SA",
    dialCode: "+966",
    flag: "https://flagcdn.com/sa.svg",
  },
  {
    name: "Senegal",
    code: "SN",
    dialCode: "+221",
    flag: "https://flagcdn.com/sn.svg",
  },
  {
    name: "Serbia",
    code: "RS",
    dialCode: "+381",
    flag: "https://flagcdn.com/rs.svg",
  },
  {
    name: "Singapore",
    code: "SG",
    dialCode: "+65",
    flag: "https://flagcdn.com/sg.svg",
  },
  {
    name: "Slovakia",
    code: "SK",
    dialCode: "+421",
    flag: "https://flagcdn.com/sk.svg",
  },
  {
    name: "Slovenia",
    code: "SI",
    dialCode: "+386",
    flag: "https://flagcdn.com/si.svg",
  },
  {
    name: "Somalia",
    code: "SO",
    dialCode: "+252",
    flag: "https://flagcdn.com/so.svg",
  },
  {
    name: "South Africa",
    code: "ZA",
    dialCode: "+27",
    flag: "https://flagcdn.com/za.svg",
  },
  {
    name: "Spain",
    code: "ES",
    dialCode: "+34",
    flag: "https://flagcdn.com/es.svg",
  },
  {
    name: "Sri Lanka",
    code: "LK",
    dialCode: "+94",
    flag: "https://flagcdn.com/lk.svg",
  },
  {
    name: "Sudan",
    code: "SD",
    dialCode: "+249",
    flag: "https://flagcdn.com/sd.svg",
  },
  {
    name: "Sweden",
    code: "SE",
    dialCode: "+46",
    flag: "https://flagcdn.com/se.svg",
  },
  {
    name: "Switzerland",
    code: "CH",
    dialCode: "+41",
    flag: "https://flagcdn.com/ch.svg",
  },
  {
    name: "Syria",
    code: "SY",
    dialCode: "+963",
    flag: "https://flagcdn.com/sy.svg",
  },
  {
    name: "Taiwan",
    code: "TW",
    dialCode: "+886",
    flag: "https://flagcdn.com/tw.svg",
  },
  {
    name: "Tajikistan",
    code: "TJ",
    dialCode: "+992",
    flag: "https://flagcdn.com/tj.svg",
  },
  {
    name: "Tanzania",
    code: "TZ",
    dialCode: "+255",
    flag: "https://flagcdn.com/tz.svg",
  },
  {
    name: "Thailand",
    code: "TH",
    dialCode: "+66",
    flag: "https://flagcdn.com/th.svg",
  },
  {
    name: "Togo",
    code: "TG",
    dialCode: "+228",
    flag: "https://flagcdn.com/tg.svg",
  },
  {
    name: "Trinidad and Tobago",
    code: "TT",
    dialCode: "+1",
    flag: "https://flagcdn.com/tt.svg",
  },
  {
    name: "Tunisia",
    code: "TN",
    dialCode: "+216",
    flag: "https://flagcdn.com/tn.svg",
  },
  {
    name: "Turkey",
    code: "TR",
    dialCode: "+90",
    flag: "https://flagcdn.com/tr.svg",
  },
  {
    name: "Turkmenistan",
    code: "TM",
    dialCode: "+993",
    flag: "https://flagcdn.com/tm.svg",
  },
  {
    name: "Uganda",
    code: "UG",
    dialCode: "+256",
    flag: "https://flagcdn.com/ug.svg",
  },
  {
    name: "Ukraine",
    code: "UA",
    dialCode: "+380",
    flag: "https://flagcdn.com/ua.svg",
  },
  {
    name: "United Arab Emirates",
    code: "AE",
    dialCode: "+971",
    flag: "https://flagcdn.com/ae.svg",
  },
  {
    name: "United Kingdom",
    code: "GB",
    dialCode: "+44",
    flag: "https://flagcdn.com/gb.svg",
  },
  {
    name: "United States",
    code: "US",
    dialCode: "+1",
    flag: "https://flagcdn.com/us.svg",
  },
  {
    name: "Uruguay",
    code: "UY",
    dialCode: "+598",
    flag: "https://flagcdn.com/uy.svg",
  },
  {
    name: "Uzbekistan",
    code: "UZ",
    dialCode: "+998",
    flag: "https://flagcdn.com/uz.svg",
  },
  {
    name: "Venezuela",
    code: "VE",
    dialCode: "+58",
    flag: "https://flagcdn.com/ve.svg",
  },
  {
    name: "Yemen",
    code: "YE",
    dialCode: "+967",
    flag: "https://flagcdn.com/ye.svg",
  },
  {
    name: "Zambia",
    code: "ZM",
    dialCode: "+260",
    flag: "https://flagcdn.com/zm.svg",
  },
  {
    name: "Zimbabwe",
    code: "ZW",
    dialCode: "+263",
    flag: "https://flagcdn.com/zw.svg",
  },
];

export default countries;
